swagger: "2.0"
info:
  title: Whatever
  version: 1.0.0
host: localhost:1234
paths:
  /foo:
    post:
      operationId: doFoo
      x-scala-package: foo
      parameters:
      - in: query
        name: long
        type: integer
        format: int64
      - in: body
        name: body
        schema:
          $ref: '#/definitions/defLong'
      responses:
        '201':
          description: "woop"
          schema:
            $ref: '#/definitions/defLong'
definitions:
  defLong:
    type: integer
    format: int64
  defArrayLong:
    type: array
    items:
      type: integer
      format: int64
  defArrayArrayLong:
    type: array
    items:
      $ref: '#/definitions/defArrayLong'
  propRef:
    type: object
    properties:
      param:
        $ref: "#/definitions/defLong"
      array:
        $ref: "#/definitions/defArrayLong"
      arrayArray:
        $ref: "#/definitions/defArrayArrayLong"
